#!/usr/bin/env python3
# splitmbox: split mbox data into email files, reading from stdin

import sys
import re

try:
    prefix = sys.argv[1]
except IndexError:
    prefix = "msg_"

try:
    suffix = sys.argv[2]
except IndexError:
    suffix = ".eml"

i = 0
try:
    for line in sys.stdin:
        if re.match("From:", line):
            i += 1
            try:
                file.close()
            except NameError:
                pass
            file = open(f"{prefix}{i}{suffix}", "w")
        try:
            file.write(line)
        except NameError:
            pass
finally:
    if file:
        file.close()
